export type SecurityEventType =
  | "LOGIN_FAILED"
  | "LOGIN_SUCCESS"
  | "LOGIN_TOO_MANY_ATTEMPTS"
  | "GOOGLE_LOGIN_REQUIRED"
  | "GOOGLE_LOGIN_SUCCESS"
  | "GOOGLE_ACCOUNT_CREATED"
  | "GOOGLE_ACCOUNT_LINKED"
  | "LOGIN_BLOCKED_UNVERIFIED" 
  | "LOGIN_BLOCKED_BANNED"
  | "LOGOUT"
  | "SESSION_REVOKED_BANNED"
  | "SIGNUP_SUCCESS"
  | "SIGNUP_CAPTCHA_FAILED"  
  | "SIGNUP_EMAIL_EXISTS" 
  | "SIGNUP_RESEND_LIMIT_REACHED"
  | "SIGNUP_COOLDOWN_ACTIVE"
  | "SIGNUP_LOCAL_AUTH_LINKED"
  | "PASSWORD_RESET_BLOCKED_BANNED"
  | "LOCAL_AUTH_REQUIRED" //FOR FORGOT PASSWORD 
  | "OTP_REQUESTED"
  | "OTP_COOLDOWN_ACTIVE"
  | "OTP_LIMIT_REACHED"
  | "INVALID_OTP"
  | "OTP_EXPIRED"
  | "OTP_TOO_MANY_ATTEMPTS"
  | "OTP_VERIFIED"
  | "PASSWORD_RESET_SESSION_EXPIRED"
  | "PASSWORD_RESET_SAME_PASSWORD"
  | "PASSWORD_RESET_SUCCESS"
  | "RATE_LIMIT_EXCEEDED"
  | "ROLE_INVITE_CREATED"
  | "INVITE_ACCEPTED"
  | "USER_BANNED"
  | "USER_UNBANNED"
  | "ROLE_PROMOTED"
  | "ROLE_DEMOTED"
  | "AUDIT_EXPORTED";

export interface SecurityEventPayload {
  event: SecurityEventType;
  email?: string;
  userId?: string;
  ip?: string;
  [key: string]: unknown;
}